.\"  Copyright (C) 2007-2009 Ruben Pollan Bella <meskio@sindominio.net>         
.\"  Copyright (C) 2010 Enrique Matías Sánchez <cronopios@gmail.com>
  
.\"                                                                        
.\"   This file is part of TuDu.                                           
.\"                                                                        
.\"   TuDu is free software; you can redistribute it and/or modify         
.\"   it under the terms of the GNU General Public License as published by 
.\"   the Free Software Foundation; version 3 of the License.       
.\"                                                                        
.\"   TuDu is distributed in the hope that it will be useful,              
.\"   but WITHOUT ANY WARRANTY; without even the implied warranty of       
.\"   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        
.\"   GNU General Public License for more details.                         
.\"                                                                        
.\"   You should have received a copy of the GNU General Public License    
.\"   along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH TuDu 1 "January 09, 2010" Unix "User Manuals"
.SH NAME
TuDu \- A command-line tool to manage TODO lists hierarchically.
.SH SYNOPSIS
.PP 
\fBtudu \fR[\fB-f \fItudu_file\fR] [\fB-c \fIconfig_file\fR] [\fB-v[v]\fR]
[\fB-h\fR]
.SH DESCRIPTION
.PP
\fBTuDu\fR is a commandline tool to manage hierarchical TODO lists, so that you
can organize everything you have to do in a simple and efficient way. 
It does not use any database backend, but plain XML files.

Every TODO is composed by:
.TS
tab (>);
l l.
Status>Currently only two options: Pending and Done.
Title>A short sentence summarizing the task.
Description text>A longer text providing more details. (Optional)
Priority>The urgency of the task. (Optional)
Category>A short tag such as @home, @work, @inet. (Optional)
Deadline>The latest date the task should be done. (Optional)
Scheduled date>The planned date to do the task. (Optional)
Subtasks>Every task can have any number of subtasks. (Optional)
.TE

Tasks can be ordered by any of those fields, and categories can be used to show
only some certain kinds of tasks. Tudu also warns when a deadline is
approaching, and shows the percentage of the task done so far.
.SH OPTIONS
.IP "-f \fItudu_file\fP" 10
Load the given tudu file
.IP "-c \fIconfig-file\fP" 10
Load specific config file
.IP "-v" 10
Display the TuDu version number.
.IP "-vv" 10
Display license and copyright information.
.IP "-h" 10
Display help.
.SH INTERFACE
All the key bindings described here are the defaults in tudu. They can be
changed in the config file.
.IP h
Move the cursor one level out in the tree depth.
.IP l
Move the cursor one level in in the tree depth.
.IP j
Move the cursor to the next task.
.IP k
Move the cursor to the previous task.
.IP J
Move a task one position down.
.IP K
Move a task one position up.
.IP m
Mark a task as done.
.IP dd
Delete a task.
.IP dt
Remove the deadline of the task.
.IP df
Remove the priority of the task.
.IP dS
Remove the scheduled date of the task.
.IP p
Paste the last deleted task under the current cursor line.
.IP P
Paste the last deleted task over the current cursor line.
.IP V
Paste the last deleted task as a subtask of the currently selected task.
.IP o
Add new task.
.IP O
Add a new task over the current cursor line.
.IP a
Edit the title of the task.
.IP t
Edit the deadline.
.IP f
Set the priority of the task.
.IP C
Add or modify the category of the task.
.IP e
Edit the description text of the task.
.IP x
Scroll the text window upwards.
.IP z
Scroll the text window downwards.
.IP S
Edit the scheduled date of the task.
.IP X
Scroll the schedule window upwards.
.IP Z
Scroll the schedule window downwards.
.IP c
Collapse or expand the children of the current task.
.IP M
Hide or show tasks marked as done.
.IP /
Search for a pattern in tasks titles.
.IP n
Search the next occurrence of last search.
.IP N
Search the previous occurrence of the last searched tasks.
.IP /
Search for a pattern in tasks titles.
.IP n
Search the next occurrence of last search.
.IP N
Search the previous occurrence of the last search.
.IP :
Open the command input. See the COMMANDS section.
.IP bt
Sort by title.
.IP bT
Sort by title in reverse order.
.IP bd
Sort by done.
.IP bD
Sort by done in reverse order.
.IP bl
Sort by deadline.
.IP bL
Sort by deadline in reverse order.
.IP bp
Sort by priority.
.IP bP
Sort by priority in reverse order.
.IP bc
Sort by category.
.IP bC
Sort by category in reverse order.
.IP bu
Sort by user-defined order.
.IP bU
Sort by reversed user-defined order.
.IP bd
Sort by done.
.IP bD
Sort by done in reverse order.
.IP bl
Sort by deadline.
.IP bL
Sort by deadline in reverse order.
.IP bp
Sort by priority.
.IP bP
Sort by priority in reverse order.
.IP bc
Sort by category.
.IP bC
Sort by category in reverse order.
.IP bu
Sort by user.
.IP bU
Sort by user in reverse order.
.IP s
Save all the changes.
.IP ?
Display the help.
.IP q
Quit tudu saving the last changes.
.IP Q
Quit tudu without saving anything.
.SH COMMANDS
.IP "hide category1 category2 ... categoryN"
Hide one or more categories.
.IP "show category1 category2 ... categoryN"
Display one or more categories.
.IP showall
Display all the categories.
.IP "showonly category1 category2 ... categoryN"
Hide all the categories except the ones given.
.IP "help"
Display the man page.
.SH CONFIG
The config file have several sections which start by a name between brackets,
like \fB[ general ]\fR. Other config files can be included with the option:
.IP "@include = 'path'"

.PP
The options of each section are:

.SS general
.IP "collapse = yes|no"
Collapse the tasks by default.
.IP "hide_done = yes|no"
Whether to hide tasks marked as done.
.IP "hide_percent = yes|no"
Whether to hide the percentage display on each task.
.IP "visual_tree = yes|no"
Toggle graphical tree. It shows marks, like \fB(+)\fR at the left of the tasks.
It is necessary in some shells that can not display bold characters.
.IP "loop_move = yes|no"
Whether to jump to the beginning (or end) when the end (or beginning) is reached.
.IP "days_warn = number"
How many days before the task is due will the deadline sport a warning remark.
.IP "us_dates = yes|no"
Use US date format (mm/dd/yyyy), by default it uses dd/mm/yyyy.
.IP "sort_order = string"
Default order in which tasks will be shown. Tasks are ordered by the 1st letter
in the string, then by the 2nd, and so on.

The letters mean:
.RS
.IP t
title
.IP T
reverse title
.IP d
done
.IP D
reverse done
.IP l
deadline
.IP L
reverse deadline
.IP c
category
.IP C
reverse category
.IP e
percentage done
.IP E
reverse percentage done
.IP u
user-defined order
.IP U
reverse user-defined order
.RE
.IP "editor = 'path_bin %s'"
.SS keys
This section defines any key binding on the program. See the example in the
default config file.
.SS theme
Window positions are described by rows; each row with the syntax:
.RS
row = [height]([width|]window[, [width|]window, ...])
.RE
The height and width can be the number of characters or a percentage followed by
\fB%\fR. The possible windows are: help, tree, info, blank, vpipe, hpipe text, 
and schedule. The windows help, vpipe and info don't need to have height, neither 
hpipe needs to have width, because is predefined as 1.
TuDu will try to guess the non given information.

Other options for the theme are:
.IP "columns = colm1,...,colmN"
Columns in tree window. The possible columns are: title, priority, category and
deadline.
.IP "color = color_text, color_background"
The default colors for the text and background. The colors can be defined as
\fB(r, g, b)\fR, where r, g and b are numbers from 0 to 1000, or with the words:
black, red, green, yellow, blue, magenta, cyan, white, transparent.
.IP "window = color_text, color_background"
For each window can be defined it's own colors. The colors of vpipe and hpipe are
the same, and defined with the window name \fBpipe\fR.
.IP "selected = color_text, color_background"
Color for the items under the cursor.
.IP "deadlineMark = color_text, color_background"
Color for the mark of deadline soon.
.SH FILES
.PP
.IP "~/.tudurc"
User configuration file.
.IP "/etc/tudurc"
Global configuration file.
.IP "~/.tudu.xml"
User default tudu.
.SH NO WARRANTIES
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.SH SEE ALSO
.PP
TuDu Home Page: http://www.cauterized.net/~meskio/tudu/
.SH AUTHOR
TuDu was written by Rub\['e]n Poll\['a]n Bella <meskio@sindominio.net>.
.PP
This manual page was written by Rub\['e]n Poll\['a]n Bella and further
improved by Enrique Mat\['i]as S\['a]nchez.
